application: plateau
version: 1
runtime: php55
api_version: 1

handlers:


- url: /Stylesheets
  static_dir: Stylesheets


- url: /
  script: home.php
  
- url: /home
  script: home.php
  
- url: /signup
  script: signup.php

- url: /register
  script: register.php
  
- url: /login
  script: login.php
  
- url: /aboutus
  script: aboutus.php
  
- url: /dashboard
  script: dashboard.php

- url: /loginuser
  script: loginuser.php
  
- url: /logout
  script: logout.php
  
- url: /submit
  script: submitcontent.php

- url: /confirmsubmit
  script: submitcontentdb.php
  
- url: /analytics
  script: ajax_analytics.php

- url: /postinfo
  script: ajax_postinfo.php  
  
- url: /forgot
  script: forgotpassword.php

- url: /editcontent
  script: contentedit.php  
  
- url: /contenteditconfirm
  script: contenteditconfirm.php 

- url: /editprofile
  script: changepass.php   
  
- url: /changepassworddb
  script: changepassconfirm.php

- url: /forgotconfirm
  script: forgotpasswordconfirm.php  
  
- url: /faq
  script: faq.php  
  
- url: /aboutus
  script: aboutus.php

- url: /sitemap.xml
  static_files: Stylesheets/sitemap.xml
  upload: Stylesheets/sitemap.xml


  
  